# Generated by Django 5.2.3 on 2025-06-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.FloatField()),
                ('tax', models.FloatField(default=1.106470588)),
                ('actualamount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalAcutalamount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalacutalamount', models.FloatField()),
            ],
        ),
    ]
